Feature/64bit (#62)
* Add required type conversion

On 64bit gnu_dev_makedev returns UInt64, but mknod
expects UInt:

Sources/Mailbox.swift:178:42: error: cannot convert value of type 'UInt64' to \
expected argument type '__dev_t' (aka 'UInt')

* Fix Swift 4.1 warning wrt `characters`

String's do not have the characters collection anymore.